from pylatex import Document, NoEscape, NewPage, Package, Command
from modules import system_defences, user_accounts, persistences
from modules.appendix import appendix
from modules.network import network
from modules.processes import processes
import sys
import argparse
import textwrap

if __name__ == '__main__':

    # ***** Setting up the CLI argparse arguments *****
    parser = argparse.ArgumentParser(
        description='OSX Reporter.',
        epilog=textwrap.dedent('''Generates a PDF analysis report from the collected data generated by the OSXInvestigator'''))

    parser.add_argument('-v', '--verbose', action="store_true", help="Generates a longer, more detailed version of the report.")

    args = parser.parse_args()


    geometry_options = {
        "head": "40pt",
        "margin": "0.5in",
        "bottom": "0.6in",
        "includeheadfoot": True
    }

    doc = Document(geometry_options=geometry_options)
    doc.packages.append(Package('seqsplit'))

    data_location = '/output'


    system_defences(doc, data_location)
    user_accounts(doc, data_location)
    persistences(doc, data_location, args)
    #network(doc, data_location)
    #processes(doc, data_location)

    doc.generate_pdf(filepath=f"{data_location}/OSX Forensics Report", clean_tex=False)



